conversation_data = {
    "Spanish Phrase": [
        'Ayer fui a la tienda.',
        'Anoche estudié dos horas.',
        '¿Viste la película?',
        'Visité a mi familia el fin de semana pasado.',
        'No entendí lo que dijiste.',
        '¿Dónde estabas esta mañana?',
        'Vi una puesta de sol preciosa.',
        'Trabajé en mi proyecto todo el día.',
        '¿Oíste las noticias?',
        'No tuve tiempo de terminarlo.',
        '¿Qué has desayunado?',
        'He comido un bocadillo.',
        'Ayer perdí las llaves.',
        'Olvidé llamarte.',
        'Anoche estaba muy cansada.',
        'Me acosté pronto.',
        'Quedamos en una cafetería.',
        'Me encantó el libro que me recomendaste.',
        'Ayer no me gustó el tiempo.',
        '¿Te gustó el concierto?',
        'Estoy aprendiendo un nuevo idioma.',
        '¿Qué haces ahora?',
        'Estoy leyendo un libro.',
        'Hoy me siento muy bien.',
        '¿Quieres venir con nosotros?',
        'Trabajo como desarrollador de software.',
        'Vivo en un apartamento pequeño.',
        'Voy al gimnasio todas las mañanas.',
        '¿Sueles desayunar?',
        'Me gusta tomar café por la mañana.',
        '¿Dónde se encuentra ahora?',
        'En mi despacho.',
        '¿Tiene mascota?',
        'No entiendo esta pregunta.',
        '¿Puedes ayudarme con esto?',
        'No tengo planes para hoy.',
        'Hace buen tiempo.',
        'Afuera está lloviendo.',
        '¿Sabes cómo llegar?',
        'Estoy pensando en dar un paseo.',
        'Te llamaré mañana.',
        'Iremos al parque más tarde.',
        '¿Vendrás a la fiesta?',
        'Terminaré este proyecto la semana que viene.',
        '¿Qué harás este fin de semana?',
        'Voy a visitar a mis padres.',
        'Pronto te enviaré el documento.',
        '¿Estarás en la reunión?',
        'Te ayudaré con eso.',
        'Voy a empezar un nuevo hobby.',
        '¿Dónde nos reuniremos?',
        'No sé qué me pondré mañana.',
        'Te lo diré más tarde.',
        'Te recogeré a las 5.',
        '¿Vas a ver el partido?',
        'Creo que lloverá mañana.',
        'Esta noche me voy pronto a la cama.',
        'Hablaremos pronto.',
        'Estoy planeando estudiar en el extranjero.',
        '¿Qué vas a hacer ahora?',
        'He estado aprendiendo español',
        'Traducción realizada con la versión gratuita del traductor DeepL.com',
        '¿Has estado antes en este restaurante?',
        'Nunca he probado el sushi.',
        'Estaba pensando en nuestra última conversación.',
        'Mañana trabajaré hasta tarde.',
        '¿Has terminado ya los deberes?',
        'Acabo de empezar un nuevo libro.',
        'Iba a llamarte pero se me olvidó.',
        '¿Has viajado alguna vez al extranjero?',
        'Te estaba esperando.',
        'Pronto me iré.',
        'Estuve trabajando todo el día antes de tomarme un descanso.',
        'Mañana lo habré terminado.',
        'Aún no me he decidido.',
        '¿Has oído lo que han dicho?',
        'No sé si me gustará.',
        'Esperaba verte.',
        'Han estado planeando esto durante meses.',
        'Lo pasaremos muy bien juntos.',
        '¿Qué hacías ayer?',
        '¿Qué haces ahora?',
        '¿Qué harás mañana?',
        '¿Has terminado tu trabajo?',
        '¿Has ido a la reunión?',
        '¿Vienes con nosotros?',
        '¿Me ayudas con esto?',
        '¿A qué hora has llegado?',
        '¿A qué hora nos vamos?',
        '¿A qué hora llegarás?',
        'No sabía que estabas aquí.',
        'He estado pensando en esa idea.',
        'Nunca olvidaré este momento.',
        'Me sorprendió mucho tu respuesta.',
        'Estoy deseando que llegue nuestro viaje.',
        'Nos vamos a divertir mucho.',
        'Siempre recordaré el tiempo que pasamos juntos.',
        'No esperaba verte aquí.',
        '¿Ya revisaste tu correo electrónico?',
        'Haré todo lo posible por ayudarte.'
    ],
    "English Translation": [
        'I went to the store yesterday.',
        'I studied for two hours last night.',
        'Did you watch the movie?',
        'I visited my family last weekend.',
        'I didn’t understand what you said.',
        'Where were you this morning?',
        'I saw a beautiful sunset.',
        'I worked on my project all day.',
        'Did you hear the news?',
        'I didn’t have time to finish it.',
        'What did you eat for breakfast?',
        'I had a sandwich for lunch.',
        'I lost my keys yesterday.',
        'I forgot to call you.',
        'I was really tired last night.',
        'I went to bed early.',
        'We met at a coffee shop.',
        'I loved the book you recommended.',
        'I didn’t like the weather yesterday.',
        'Did you enjoy the concert?',
        'I am learning a new language.',
        'What are you doing now?',
        'I’m reading a book.',
        'I’m feeling great today.',
        'Do you want to join us?',
        'I work as a software developer.',
        'I live in a small apartment.',
        'I go to the gym every morning.',
        'Do you usually eat breakfast?',
        'I like to drink coffee in the morning.',
        'Where are you right now?',
        'I am sitting at my desk.',
        'Do you have a pet?',
        'I don’t understand this question.',
        'Can you help me with this?',
        'I don’t have any plans for today.',
        'The weather is beautiful.',
        'It’s raining outside.',
        'Do you know how to get there?',
        'I’m thinking about taking a walk.',
        'I will call you tomorrow.',
        'We’re going to the park later.',
        'Are you coming to the party?',
        'I’ll finish this project by next week.',
        'What will you do this weekend?',
        'I’m planning to visit my parents.',
        'I’ll send you the document soon.',
        'Will you be at the meeting?',
        'I’ll help you with that.',
        'I’m going to start a new hobby.',
        'Where will we meet?',
        'I’m not sure what I’ll wear tomorrow.',
        'I’ll let you know later.',
        'I’ll pick you up at 5.',
        'Are you going to watch the game?',
        'I think it will rain tomorrow.',
        'I’m going to bed early tonight.',
        'I’ll talk to you soon.',
        'I’m planning to study abroad.',
        'What are you going to do next?',
        'I have been learning Spanish.',
        'I’ve already eaten breakfast.',
        'Have you been to this restaurant before?',
        'I’ve never tried sushi.',
        'I was thinking about our last conversation.',
        'I’ll be working late tomorrow.',
        'Have you finished your homework yet?',
        'I’ve just started a new book.',
        'I was going to call you but forgot.',
        'Have you ever traveled abroad?',
        'I’ve been waiting for you.',
        'I’ll be leaving soon.',
        'I had been working all day before I took a break.',
        'I will have finished this by tomorrow.',
        'I haven’t made up my mind yet.',
        'Did you hear what they said?',
        'I’m not sure if I’ll like it.',
        'I was hoping to see you.',
        'They’ve been planning this for months.',
        'We’ll have a great time together.',
        'What were you doing yesterday?',
        'What are you doing right now?',
        'What will you do tomorrow?',
        'Have you finished your work?',
        'Did you go to the meeting?',
        'Are you coming with us?',
        'Will you help me with this?',
        'What time did you arrive?',
        'What time are we leaving?',
        'What time will you get here?',
        'I didn’t know you were here.',
        'I’ve been thinking about that idea.',
        'I’ll never forget this moment.',
        'I was really surprised by your answer.',
        'I’m looking forward to our trip.',
        'We’re going to have so much fun.',
        'I’ll always remember our time together.',
        'I didn’t expect to see you here.',
        'Have you already checked your email?',
        'I’ll try my best to help you.'
    ],
}
