
data_longer = {
    "Spanish Phrase": [
        "Iba a ir allí, pero cambié de opinión en el último momento.",
        "Voy a ir allí mañana temprano para ver el amanecer.",
        "Iría allí si tuviera más tiempo y dinero para el viaje.",
        "No me gustó mucho esa película; esperaba algo diferente.",
        "No me gusta mucho este lugar porque siempre está lleno de gente.",
        "No me gustaría mucho vivir en una ciudad tan grande y ruidosa.",
        "Quería decirte algo importante, pero me olvidé completamente.",
        "Quiero decirte algo que creo que te hará muy feliz.",
        "Querría decirte algo, pero no sé si es el momento adecuado.",
        "Lo vi ayer en el centro comercial mientras compraba ropa.",
        "Lo veo ahora con más claridad después de haber hablado contigo.",
        "Lo vería si pudiera, pero tengo que trabajar todo el día.",
        "Te dije que sí porque pensé que te haría feliz.",
        "Te digo que sí, pero espero que no cambies de opinión.",
        "Te diría que sí sin pensarlo si fuera posible.",
        "Estaba esperando el autobús cuando comenzó a llover.",
        "Estoy esperando el resultado del examen con muchas ansias.",
        "Estaría esperando si no fuera por la llamada que recibí.",
        "Pensaba en eso cuando de repente recordé otra cosa.",
        "Pienso en eso cada vez que paso por ese lugar.",
        "Pensaría en eso si tuviera un poco más de tiempo.",
        "Intenté hacerlo de la manera que me sugeriste, pero no funcionó.",
        "Intento hacerlo todos los días, aunque a veces es difícil.",
        "Intentaría hacerlo si tuviera las herramientas adecuadas.",
        "Salí temprano para evitar el tráfico y llegar a tiempo.",
        "Salgo temprano todos los días para hacer ejercicio en el parque.",
        "Saldría temprano si no tuviera tantas reuniones.",
        "Vine para ayudarte a organizar todo antes del evento.",
        "Vengo para ayudarte con lo que necesites hoy.",
        "Vendría para ayudarte si no estuviera tan ocupado.",
        "Lo hice ayer después de pensarlo detenidamente.",
        "Lo hago ahora porque no quiero dejarlo para más tarde.",
        "Lo haría si pudiera encontrar a alguien que me ayude.",
        "Me sentía cansado después de trabajar todo el día.",
        "Me siento cansado, pero tengo que terminar esto antes de dormir.",
        "Me sentiría cansado si no descansara bien cada noche.",
        "Escuché eso en las noticias esta mañana y me preocupó.",
        "Escucho eso a menudo, pero no estoy seguro de si es cierto.",
        "Escucharía eso con atención si fuera realmente importante.",
        "Te pedí ayuda porque sabía que podrías resolverlo.",
        "Te pido ayuda con esto porque es algo muy complicado.",
        "Te pediría ayuda si no pensara que estás ocupado.",
        "Lo encontré difícil al principio, pero luego fue más fácil.",
        "Lo encuentro difícil cada vez que lo intento, pero sigo intentando.",
        "Lo encontraría difícil si no tuviera experiencia previa.",
        "Pensé que sí, pero ahora tengo dudas sobre esa decisión.",
        "Pienso que sí, aunque es solo mi opinión personal.",
        "Pensaría que sí, pero depende de cómo lo mires.",
        "Estaba a punto de irme cuando me llamaste para hablar.",
        "Estoy a punto de irme, así que dime lo que necesitas rápido.",
        "Estaría a punto de irme si no estuviera esperando a alguien."
    ],
    "English Translation": [
        "I was going to go there, but I changed my mind at the last moment.",
        "I am going there early tomorrow to see the sunrise.",
        "I would go there if I had more time and money for the trip.",
        "I didn't like that movie much; I expected something different.",
        "I don't like this place much because it's always crowded.",
        "I wouldn't like living in such a big and noisy city.",
        "I wanted to tell you something important, but I completely forgot.",
        "I want to tell you something that I think will make you very happy.",
        "I would like to tell you something, but I don’t know if it’s the right moment.",
        "I saw him yesterday at the mall while I was shopping for clothes.",
        "I see it more clearly now after talking to you.",
        "I would see it if I could, but I have to work all day.",
        "I told you yes because I thought it would make you happy.",
        "I'm telling you yes, but I hope you won’t change your mind.",
        "I would tell you yes without thinking if it were possible.",
        "I was waiting for the bus when it started to rain.",
        "I’m eagerly waiting for the exam results.",
        "I would be waiting if not for the call I received.",
        "I was thinking about that when I suddenly remembered something else.",
        "I think about that every time I pass by that place.",
        "I would think about it if I had a little more time.",
        "I tried to do it the way you suggested, but it didn't work.",
        "I try to do it every day, though sometimes it's difficult.",
        "I would try to do it if I had the right tools.",
        "I left early to avoid traffic and arrive on time.",
        "I leave early every day to exercise in the park.",
        "I would leave early if I didn’t have so many meetings.",
        "I came to help you organize everything before the event.",
        "I'm here to help you with whatever you need today.",
        "I would come to help if I weren’t so busy.",
        "I did it yesterday after thinking it over carefully.",
        "I'm doing it now because I don't want to leave it for later.",
        "I would do it if I could find someone to help me.",
        "I felt tired after working all day.",
        "I feel tired, but I need to finish this before going to sleep.",
        "I would feel tired if I didn’t get enough rest each night.",
        "I heard that on the news this morning, and it worried me.",
        "I hear that often, but I'm not sure if it’s true.",
        "I would listen closely if it were truly important.",
        "I asked you for help because I knew you could solve it.",
        "I’m asking for help with this because it’s very complicated.",
        "I would ask for help if I didn’t think you were busy.",
        "I found it hard at first, but then it became easier.",
        "I find it hard every time I try, but I keep trying.",
        "I would find it hard if I didn’t have prior experience.",
        "I thought so, but now I have doubts about that decision.",
        "I think so, although it’s just my personal opinion.",
        "I would think so, but it depends on how you look at it.",
        "I was about to leave when you called me to talk.",
        "I’m about to leave, so tell me what you need quickly.",
        "I would be about to leave if I weren’t waiting for someone."
    ]
}


