
data_longer_additional = {
    "Spanish Phrase": [
        "No me esperaba que dijeras eso en frente de todos los demás.",
        "Estaba pensando en llamarte, pero decidí esperar un poco más.",
        "Me gustaría mucho que vinieras a mi cumpleaños el próximo mes.",
        "Voy a ver si puedo hacer espacio en mi agenda para la reunión.",
        "Si tuviera tiempo, iría contigo a la exposición de arte mañana.",
        "Pensé que ya habías terminado el proyecto, pero veo que sigues trabajando.",
        "Estoy considerando tomar una clase adicional para mejorar mis habilidades.",
        "Lo hubiera hecho antes si supiera que era tan importante para ti.",
        "Iba a decir algo, pero me interrumpieron antes de poder hacerlo.",
        "Lo he estado pensando y creo que deberíamos cambiar de estrategia.",
        "Vine a verte porque quería hablar contigo en persona.",
        "Quisiera saber más sobre lo que estás planeando hacer en el futuro.",
        "Me hubiera gustado ir a la fiesta, pero estaba demasiado cansado.",
        "Estoy a punto de tomar una decisión, pero necesito más información.",
        "Te habrías sorprendido de lo que vi en el museo ayer.",
        "Intentaré recordar los detalles y decírtelos la próxima vez que hablemos.",
        "Te pedí ayuda porque sabía que eres experto en este tema.",
        "Voy a intentar resolverlo por mi cuenta antes de pedir ayuda.",
        "Pensé en decírselo a alguien más, pero tú eres quien mejor lo entiende.",
        "Vine aquí para ayudarte a preparar todo antes de que lleguen los invitados.",
        "Te diría la verdad si estuviera seguro de cómo reaccionarías.",
        "Llevo todo el día esperando una respuesta y aún no me han llamado.",
        "Estaría encantado de ayudarte si me explicas lo que necesitas.",
        "Lo haría con gusto si tuviera más experiencia en el tema.",
        "Voy a preparar la cena mientras esperas que llegue nuestro amigo.",
        "Si supiera dónde está, iría a buscarlo en este momento.",
        "No te preocupes, estoy seguro de que todo saldrá bien al final.",
        "Pensé en lo que dijiste y creo que tienes razón en parte.",
        "Me gustaría invitarte a cenar este fin de semana si estás disponible.",
        "Estoy buscando una solución que sea rápida y efectiva.",
        "Voy a pasar por tu casa después del trabajo para charlar un rato.",
        "Si tuviera otra oportunidad, lo haría de manera diferente.",
        "Intenté llamarte, pero no contestaste y dejé un mensaje.",
        "Estoy considerando mudarme a otra ciudad para buscar nuevas oportunidades.",
        "He estado trabajando en este proyecto durante semanas sin descanso.",
        "Si pudieras ayudarme, lo apreciaría muchísimo.",
        "Estoy tratando de entender el problema desde tu punto de vista.",
        "Pensé en ir al concierto, pero las entradas estaban agotadas.",
        "Vine a decirte que finalmente he tomado una decisión importante.",
        "Me quedé despierto hasta tarde estudiando para el examen de mañana.",
        "Si pudiera, me tomaría unas vacaciones para descansar un poco.",
        "Voy a revisar todo de nuevo para asegurarme de no cometer errores.",
        "Me sorprendió la noticia cuando la escuché por primera vez.",
        "Estoy esperando tu respuesta antes de tomar una decisión final.",
        "Te contaría lo que pasó si no fuera tan complicado de explicar.",
        "Me hubiera sentido mejor si me lo hubieras dicho antes.",
        "Voy a dedicar más tiempo a este proyecto para mejorarlo.",
        "No te preocupes, voy a intentar terminarlo a tiempo.",
        "Pensé en renunciar, pero decidí darme otra oportunidad.",
        "Me cuesta trabajo entenderlo, pero voy a seguir intentándolo.",
        "Lo habría hecho de otra manera si hubiera tenido más tiempo."
    ],
    "English Translation": [
        "I didn’t expect you to say that in front of everyone else.",
        "I was thinking of calling you, but I decided to wait a little longer.",
        "I would really like it if you came to my birthday next month.",
        "I’m going to see if I can make space in my schedule for the meeting.",
        "If I had time, I would go with you to the art exhibition tomorrow.",
        "I thought you had already finished the project, but I see you're still working.",
        "I'm considering taking an additional class to improve my skills.",
        "I would have done it sooner if I knew it was so important to you.",
        "I was going to say something, but I got interrupted before I could.",
        "I’ve been thinking about it, and I believe we should change our strategy.",
        "I came to see you because I wanted to talk to you in person.",
        "I would like to know more about what you're planning to do in the future.",
        "I would have liked to go to the party, but I was too tired.",
        "I am about to make a decision, but I need more information.",
        "You would have been surprised by what I saw at the museum yesterday.",
        "I will try to remember the details and tell you the next time we talk.",
        "I asked for your help because I knew you are an expert in this topic.",
        "I will try to solve it on my own before asking for help.",
        "I thought about telling someone else, but you understand it best.",
        "I came here to help you prepare everything before the guests arrive.",
        "I would tell you the truth if I were sure how you’d react.",
        "I’ve been waiting all day for an answer, and they still haven’t called me.",
        "I would be delighted to help you if you explain what you need.",
        "I would do it gladly if I had more experience on the subject.",
        "I’m going to prepare dinner while you wait for our friend to arrive.",
        "If I knew where he is, I would go look for him right now.",
        "Don’t worry, I’m sure everything will turn out fine in the end.",
        "I thought about what you said, and I think you are partially right.",
        "I would like to invite you to dinner this weekend if you’re available.",
        "I’m looking for a solution that’s quick and effective.",
        "I’ll stop by your place after work to chat for a while.",
        "If I had another chance, I would do it differently.",
        "I tried calling you, but you didn’t answer, so I left a message.",
        "I'm considering moving to another city to look for new opportunities.",
        "I have been working on this project for weeks without a break.",
        "If you could help me, I would greatly appreciate it.",
        "I am trying to understand the problem from your perspective.",
        "I thought about going to the concert, but the tickets were sold out.",
        "I came to tell you that I have finally made an important decision.",
        "I stayed up late studying for tomorrow’s exam.",
        "If I could, I would take a vacation to get some rest.",
        "I am going to review everything again to make sure I don’t make mistakes.",
        "The news surprised me when I heard it for the first time.",
        "I am waiting for your response before making a final decision.",
        "I would tell you what happened if it weren’t so complicated to explain.",
        "I would have felt better if you had told me earlier.",
        "I’m going to dedicate more time to this project to improve it.",
        "Don’t worry, I’ll try to finish it on time.",
        "I thought about quitting, but I decided to give myself another chance.",
        "I find it hard to understand, but I’ll keep trying.",
        "I would have done it differently if I had more time."
    ]
}
